#!/bin/sh

# hostname:ipaddress
# dua:172.16.80.49
# dub:172.16.80.48
# tu:172.16.80.47

hostname dua

mkdir /mnt/sd-mmcblk0p1
mount /dev/mmcblk0p1 /mnt/sd-mmcblk0p1

mkdir /mnt/sd-mmcblk0p2
mount /dev/mmcblk0p2 /mnt/sd-mmcblk0p2

ifconfig eth0 172.16.80.49 netmask 255.255.255.0
ping -c 1 172.16.80.30
ping -c 1 172.16.80.111
# /mnt/sd-mmcblk0p1/bin/swic-emsw-app.elf DR &

