#!/bin/sh

# hostname:ipaddress
# dua:172.16.50.11
# dub:172.16.50.12
# tu:172.16.50.13

name="tu"

hostname $name

mkdir /mnt/sd-mmcblk0p1
mount /dev/mmcblk0p1 /mnt/sd-mmcblk0p1

mkdir /mnt/sd-mmcblk0p2
mount /dev/mmcblk0p2 /mnt/sd-mmcblk0p2

rm /etc/profile.d/aliases.sh
echo "alias stopswc='killall swc-esw-app.elf'" >> /etc/profile.d/aliases.sh
echo "alias startswc='/mnt/sd-mmcblk0p1/run/swc-app-launcher $name &'" >> /etc/profile.d/aliases.sh
echo "alias checkswc='ps | grep swc'" >> /etc/profile.d/aliases.sh
echo "alias editswc='vi /mnt/sd-mmcblk0p1/run/conf/config.txt'" >> /etc/profile.d/aliases.sh
echo "alias changeswc='vi /mnt/sd-mmcblk0p1/run/swc-dev-change'" >> /etc/profile.d/aliases.sh

if [[ "$name" == "dua" ]]; then
    ifconfig eth0 172.16.50.11 netmask 255.255.255.0
fi

if [[ "$name" == "dub" ]]; then
    ifconfig eth0 172.16.50.12 netmask 255.255.255.0
fi

if [[ "$name" == "tu" ]]; then
    ifconfig eth0 172.16.50.13 netmask 255.255.255.0
fi

# ping the I/O Module to establish connection
ping -c 1 172.16.80.14

/mnt/sd-mmcblk0p1/run/swc-app-launcher $name &

/mnt/sd-mmcblk0p1/run/swc-app-monitor $name &



