/**
* $Id: EventProcessor.h 6264 2010-09-21 18:57:59Z tra18693 $
*
* Class EventProcessor is the base class for all active object 
* classes. It is derived from class Thread and provides the 
* general purpose event processing loop for a derived event 
* processor. 
*  
* A derived event processor initializes its devices, registers 
* the desire events for those devices, and then starts the task.
* Device drivers for each of the devices will wakeup the event 
* processor when devices need servicing. The base class responds 
* to the events generated by the devices and passes the event to 
* the derived class for processing. 
* 
*/
#ifndef EventProcessor_H
#define EventProcessor_H

//#include <selectLib.h>
#include <sys/select.h>
//#include <msgQLib.h>
#include <sys/times.h>
#include <map>

#include "Device.h"

// #include "Thread.h"
#include "DeviceEvent.h"
#include "DeviceFactory.h"
#include "Event.h"
// #include "Mutex.h"
// #include "Device.h"
// #include "TimerDevice.h"
#include "TimeValue.h"
// #include "ElapsedTimer.h"
// #include "Logger.h"

// Needs to be commented out in order for class EventProcessor to be included 
// by Doxygen

using namespace std;

class EventProcessor
{
public:
   /**
   * Constructor
   *
   * @param name Event processor name
   * @param priority Event processor priority (0-255, 0 = highest)
   * @param stackSize size of thread stack in bytes, default is {@link #DEFAULT_TASK_STACK}
   * @param options VxWorks task options, defaults to {@link #DEFAULT_TASK_OPTIONS}
   */
   EventProcessor();

   /**
   * Destructor
   *
   */
   virtual ~EventProcessor();

   /**
   * Method getName returns event processor name.
   *
   * @return Event processor name
   */
   inline const string &getName() const;

   /**
   * Method setSelectTimeout sets the timeout used when using 
   * the select mechanism.
   *
   * @param msec Timeout (msec)
   * @return Status of operation
   */
   STATUS setSelectTimeout(int msec);

   // /**
   //  * Sets the timeout when using the select mechanism.
   //  * @param timeout Timeout value
   //  * @return Status of operation
   //  */
//   STATUS setSelectTimeout(const int& timeout);

   /**
   * Method getTotalEvents returns total events that have occurred.
   *
   * @return Total events
   */
   inline int getTotalEvents() const;

   /** 
    * Method incTotalEvents increments and returns the resulting updated total 
    * event counter's value. 
    * @todo: This function was introduced to integrate the event processor 
    *        (task) statusing with a portion of the TBRS source code that
    *        operates based on events that are not currently a part of the EP
    *        framework.  As the TBRS task in question currently waits on these
    *        events for potentially extended periods of time (of which the
    *        upper-bound time limit is unknown, being contingent upon
    *        user-specified diagnostic parameters), the task would appear as
    *        "inactive" by the EventProcessorMgr due to the lack of EP activity.
    *        Thus, this function was implemented to provide such a task the
    *        means to update its own event status counter.  When this TBRS EP
    *        task is updated to integrate properly with the EP framework, this
    *        function should be removed.
    *  
    * @return int Increment total events.
    */
   inline int incTotalEvents();
   
   /**
   * Method initiateTermination is a virtual method that writes to 
   * the shutdown pipe to initiate termination of the thread for 
   * this event processor. 
   *  
   * A derived EventProcessor can override this method to perform 
   * any desired processing prior to sending a shutdown 
   * notification to the thread. It must call this implementation 
   * of the virtual method to ensure the thread is instructed to 
   * terminate. 
   *
   */
//   virtual void initiateTermination();

   /**
   * Method printInfo is a virtual method called when the event 
   * processor is selected in the EventProcessorMgr menu on the 
   * VxWorks shell. 
   *
   */
//   virtual void printInfo();

   /**
   * Method getTerminated returns terminated flag.
   *
   */
   inline bool getTerminated();

   /**
    * Method getSelectEarlyExitFailure() returns the current state (true=failed) 
    * of the health of the select() call. A failure state indicates that 
    * select() has repeatedly returned early (prior the specified timeout) 
    * without detection of any events. 
    * 
    */
   inline bool getSelectEarlyExitFailure();

   virtual STATUS start();

protected:

   /**
   * Method addEvent adds a device event to the event list.
   *
   * @param device Device object
   * @param eventType Event type associated with Device object
   * @param priority Event priority (lower number = higher 
   *                 priority)
   * @param eventFunc Event function to call when this event 
   *                  occurs
   * @return Status of operation
   */
   STATUS addEvent(Device &device, EventType eventType, int priority,
                   EventFunc eventFunc); 

   /**
   * Method addEvent adds a device event to the event list.
   *
   * @param device Device object
   * @param eventType Event type associated with Device object
   * @param priority Event priority (lower number = higher 
   *                 priority)
   * @param eventFuncInt Event function to call when this event 
   *                     occurs
   * @param eventParam Event parameter to pass into event function
   * @return Status of operation
   */
   STATUS addEvent(Device &device, EventType eventType, int priority,
                   EventFuncInt eventFuncInt, int eventParam); 

   /**
   * Method deleteEvent deletes a device event from the event list.
   *
   * @param device Device object
   * @param eventType Event type associated with Device object
   * @return Status of operation
   */
   STATUS deleteEvent(Device &device, EventType eventType); 

   /**
   * Method processError is a virtual method called when an error 
   * is detected by the base class. It should be implemented by the
   * derived event processor class, so that it is notified. 
   *  
   * This is only called when select has an error. This typically 
   * will be a EBADF error as a result of a closed fd that is 
   * included in a descriptor set. The base class implementation of 
   * this method will attempt to determine which fd caused the 
   * problem, so that it can be fixed in the derived class. The 
   * derived class can override the behavior of this method, and 
   * call the base class method to provide the fd check if desired.
   * This might be done to send an Alert, which can not be done 
   * from here. Because this condition should not occur with 
   * correctly implemented derived class, it will print the 
   * contents of the event list, attempt to determine which fd 
   * caused the problem, and exit the thread. 
   *
   * @param errnoValue Errno value
   */
//   virtual void processError(int errnoValue);

   /**
   * Method processWaitTimeout is a virtual method called when a 
   * timeout occurs when using the select mechanism. It should be 
   * implemented by the derived event processor class, so that it 
   * can process the timeout. 
   *
   */
   virtual void processWaitTimeout();

   /**
   * Method printEventList prints the contents of the event list to 
   * stdout. 
   *
   */
   void printEventList();

   /**
    * Create a device that can be written to.<p/>
    * The device <code>name</code> is expected to have been configured for use by
    * {@link DeviceFactory}, typically in <code>devices.conf</code>.
    * 
    * @param name name of the device to create
    */
   Device* createWriteDevice(const std::string& name)
   {
      return createDevice(name, DeviceFactory::Outbound);
      //  return createDevice(name, 1);
   }

   /**
    * Create a device that can be read from.<p/>
    * The device <code>name</code> is expected to have been configured for use by
    * {@link DeviceFactory}, typically in <code>devices.conf</code>.
    * 
    * @param name name of the device to create
    * @param callback method to call when data arrives. see {@link addEvent}
    * @param priority see {@link addEvent}
    */
   Device* createReadDevice(const std::string& name, EventFunc callback, int priority)
   {
        return createDevice(name, DeviceFactory::Inbound, callback, READ_EVENT, priority);
      //   return createDevice(name, 0, callback, READ_EVENT, priority);
   }

   // /**
   //  * Create a named timer that will invoke <code>callback</code> when it fires.
   //  * To prevent acknowledge the firing of the timer <code>callback</code>
   //  * is expected to either call {@link TimerDevice#start()} or 
   //  * {@link TimerDevice#clearExpiration()}.
   //  * 
   //  * @param name name of the timer
   //  * @param callback method to call when the timer fires. see {@link #addEvent}
   //  * @param timeout time period between start and the timer fires.
   //  * @param priority see {@link #addEvent}
   //  * @param start if <code>true</code> returned timer will be started,
   //  *           otherwise it's up to the caller to start it
   //  * @return newly created timer or NULL on failure
   //  */
   // TimerDevice* createTimer(const string& name, EventFunc callback, TimeValue timeout,
   //                          int priority = 10, bool start = false);

   // /**
   //  * Create a timer that will invoke <code>callback</code> when it fires.
   //  * To prevent acknowledge the firing of the timer <code>callback</code>
   //  * is expected to either call {@link TimerDevice#start()} or 
   //  * {@link TimerDevice#clearExpiration()}.
   //  * 
   //  * @param callback method to call when the timer fires. see {@link #addEvent}
   //  * @param timeout time period between start and the timer fires.
   //  * @param priority see {@link #addEvent}
   //  * @param start if <code>true</code> returned timer will be started,
   //  *           otherwise it's up to the caller to start it
   //  * @return newly created timer or NULL on failure
   //  */
   // TimerDevice* createTimer(EventFunc callback, TimeValue timeout, int priority = 10, 
   //                          bool start = false);

   /**
    * Create a status device that can be notified.<p/>
    * The device <code>name</code> is expected to have been configured for use by
    * {@link DeviceFactory}, typically in <code>devices.conf</code>.
    * 
    * @param name name of the device to create
    * @param callback method to call when notified. see {@link addEvent}
    * @param priority see {@link addEvent}
    */
   Device* createStatusDevice(const std::string& name, EventFunc callback, int priority)
   {
      return createDevice(name, DeviceFactory::Inbound, callback, STATUS_EVENT, priority);
      //  return createDevice(name, 0, callback, STATUS_EVENT, priority);
   }

   /**
   * Method addCounter creates a counter identified by counterId. 
   * Counters can be used as monitoring tools within the derived 
   * class. 
   *
   * @param counterId Counter identifier
   */
   void addCounter(int counterId);

   /**
   * Method incCounter increments a counter identified by 
   * counterId.
   *
   * @param counterId Counter identifier
   */
   void incCounter(int counterId);

   /**
   * Method resetCounter resets a counter identified by counterId. 
   *
   * @param counterId Counter identifier
   */
   void resetCounter(int counterId);

   /**
   * Method getCounter returns current value of counter identified 
   * by counterId. 
   *
   * @param counterId Counter identifier
   * @return Counter value
   */
   int getCounter(int counterId);

   /**
   * Method terminate sets the terminate flag.
   *
   */
   void terminate();

   /** Terminated flag */

   bool _terminated;

private:

   /**
   * Method waitOnSelect calls select to wait on device events in
   * event list.
   *
   */
   void waitOnSelect();


   /**
    * Create a device that can be notified.<p/>
    * The device <code>name</code> is expected to have been configured for use by
    * {@link DeviceFactory}, typically in <code>devices.conf</code>.
    *
    * @param name name of the device to create 
    * @param mode device mode
    * @param callback method to call when notified. see {@link #addEvent}
    * @param eventType see {@link #addEvent}
    * @param priority see {@link #addEvent}
    * @return newly created device or NULL on failure
    */
   // Device* createDevice(const std::string& name, 
   //                       int mode = 1, //outbound
   //                       EventFunc callback = NULL, 
   //                       EventType eventType = READ_EVENT, 
   //                       int priority = 10);
   Device* createDevice(const std::string& name, 
                         DeviceFactory::Mode mode = DeviceFactory::Outbound,
                         EventFunc callback = NULL, 
                         EventType eventType = READ_EVENT, 
                         int priority = 10);

   /**
   * Method clearEventList cleans up the event list.
   *
   */
   void clearEventList();

   /**
   * Method addEvent adds a device event object to the event list.
   *  
   * @param event Device event 
   * @return Status of operation 
   */
   STATUS addEvent(DeviceEvent *event);

   /**
   * Method dispatchEvent calls the appropriate function associated
   * with the event. 
   *  
   * @param event Device event 
   */
   void dispatchEvent(DeviceEvent *event);

   /**
   * Method processShutdownNotification processes a shutdown 
   * notification. 
   *  
   */
   void processShutdownNotification();

   /** Event map definition */

   typedef multimap<int, DeviceEvent *> EventMap;

   /** 
    *  Event pair definition used when inserting events into
    *  event map
    */

   typedef pair<int, DeviceEvent *> EventMapPair;

   /** Counter map definition */

   typedef map<int, int> CounterMap;

   /** Select read file descriptor set */

   fd_set _readSet;

   /** Select write file descriptor set */

   fd_set _writeSet;

   /** Select status (exception) file descriptor set */

   fd_set _statusSet;

   /** Select file set size */

   int _fdSize;

   /** Event list */

   EventMap _eventList;

   /** Total events processed */

   unsigned int _totalEventsProcessed;
   
   /** Status of select()'s non-error-error state, in which select returns with
    *  num descriptor count of 0 before _selectTimeout is expected to expire. */
   bool _selectEarlyExitFailure;

   /** Elapsed timer */

//   ElapsedTimer _execTimer;

   /** Total time executing events */

   double _totalExecTime;

   /** Average event execution time */

   double _avgExecTime;

   /** Minimum event execution time */

   double _minExecTime;

   /** Maximum event execution time */

   double _maxExecTime;

   /** Select timeout */

   struct timeval _selectTimeout;

   double _selTimeoutValue;
   
   /** Timeout in clock ticks */

   int _ticksTimeout;

   /** Timeout set flag */

   bool _timeoutSet;

   /** Counter for tracking select() early exit errors */
   int _selEarlyExitCount;
   
   /** Counters */

   CounterMap _counters;

   /** Shutdown device */

   Device _shutdownDev;
   
   std::string _name;

//   Logger *_logEvPrcr;
   
};

const string &EventProcessor::getName() const
{
   return(_name);
}

int EventProcessor::getTotalEvents() const
{
   return(_totalEventsProcessed);
}

int EventProcessor::incTotalEvents()
{
    return(++_totalEventsProcessed);
}

bool EventProcessor::getTerminated()
{
   return(_terminated);
}

bool EventProcessor::getSelectEarlyExitFailure()
{
    return(_selectEarlyExitFailure);
}

#endif

