/**
* $Id: UDPNetworkDevice.cpp 6569 2011-02-25 23:44:30Z ste38548 $
*/
//#include <sockLib.h>
//#include <usrLib.h>
#include <string.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include "UDPNetworkDevice.h"

UDPNetworkDevice::UDPNetworkDevice(NetworkSide side,
                                   const string &host,
                                   unsigned short port,
                                   bool persistArp) :
NetworkDevice(side, host, port),
arpPersisted(!persistArp)
{
}

int UDPNetworkDevice::open()
{
   // Create a socket.

   if ((_fd = socket (AF_INET, SOCK_DGRAM, 0)) == ERROR)
   {
      return(ERROR);
   }

   if (_side == NetworkServer)
   {
      // Get sockaddr information for local host.

      if (getSockaddr(_local.hostName, _local.port, _local.sockaddr) == ERROR)
      {
         close();
         return(ERROR);
      }

      // Set SO_REUSEADDR Option for Socket.

      if (setSocketOption(SO_REUSEADDR, 1) == ERROR)
      {
         close();
         return(ERROR);
      }

      // Bind the Socket.

      if (bind(_fd, (struct sockaddr *)&_local.sockaddr, 
               sizeof(_local.sockaddr)) == ERROR)
      {
         close();
         return(ERROR);
      }

   }
   else
   {
      // Get sockaddr information for remote host.

      if (getSockaddr(_remote.hostName, _remote.port, _remote.sockaddr) == ERROR)
      {
         close();
         return(ERROR);
      }
   }
   
// outputSocketInfo();

   return(OK);
}

int UDPNetworkDevice::read(
   char *buffer,     
   size_t maxBytes,  
   size_t &bytesRead,
   struct sockaddr &from
)
{
	int status;

   unsigned int size = sizeof(from);
   status = recvfrom(_fd, buffer, maxBytes, 0, &from, &size);
   if (status == ERROR)
   {
      bytesRead = 0;
      return(ERROR);
   }

   bytesRead = static_cast<size_t>(status);
   return(OK);
}

int UDPNetworkDevice::write(
   const void *buffer,           
   size_t numBytes,        
   struct sockaddr_in &to, 
   size_t &bytesWritten    
)
{
	int status;
   
   // if we haven't persisted ARP (& that we're been told to persist it)
   // then attempt it.
   // intent is that the ARP entry becomes resolved and permanent before the first 
   // UDP packet goes to that host (resolving the issue of initial packets getting dropped
   // until ARP is resolved)
   if (!arpPersisted)
   {
      // go ahead and say that it's been persisted
      // this will cause the first call to fail if we can't persist arp
      // (alerts generated by caller, etc.) but subsequent write attempts
      // will either go through or drop on the floor (as typically expected with UDP)   
      arpPersisted = true;

      // Attempt to make ARP entry permanent.
      // Note: We do not return an error if an error occurs here, as there are int
      //       cases in which arpResolve will fail for valid destination 
      //       addresses. For example, VxWorks does not add destination 
      //       addresses of differing subnets to the local ARP table, instead 
      //       adding the gateway address to the ARP table, with the destination 
      //       stored in the route table. Additionally, the ARP resolve is an 
      //       attempt, for which, if it fails, we'll still want to attempt to 
      //       send the packet to the destination. 
      if (NetworkDevice::resolveArp(_remote.hostName) != OK)
      {
         printf("********************************************************************************\n"
                "**** UDPNetworkDevice::write():\n"
                "****   - Unable to create permanent ARP entry for %s: errno = %s\n"
                "********************************************************************************\n", 
                _remote.hostName.c_str(), strerror(errno));
      }
      
   }

   // Data buffer pointer in sendto system call is "char *", need to
   // convert const void * to char *. This hides the non-constantness
   // from the users of this class.

   char *charBufPtr = static_cast<char *>(const_cast<void *>(buffer));

   status = sendto(_fd, charBufPtr, numBytes, 0, 
                   (struct sockaddr *)&to, sizeof(struct sockaddr));
   if (status == ERROR)
   {
//      printf("\n"
//            "********************************************************************************\n"
//            "***** sendTo() failed for message to %s (numBytes=%d):\n"
//            "*****          - errno = %s.\n"
//            "********************************************************************************\n",
//            _remote.hostName.c_str(), numBytes, strerror(errnoGet()));
//      printf("================================================================================\n"
//             "==== Dump of buffer (numBytes=%d):\n", numBytes);
//      d(reinterpret_cast<char *>(charBufPtr),numBytes/sizeof(int), sizeof(int));
//      printf("================================================================================\n");
      outputSocketInfo();
      bytesWritten = 0;
      return(ERROR);
   }

   bytesWritten = static_cast<size_t>(status);
   return(OK);
}

int UDPNetworkDevice::read(
   char *buffer,     
   size_t maxBytes,  
   size_t &bytesRead 
)
{
   return (read(buffer, maxBytes, bytesRead, _from));
}

int UDPNetworkDevice::write(
   const void *buffer,  
   size_t numBytes,     
   size_t &bytesWritten 
)
{
   return(write(buffer, numBytes, _remote.sockaddr, bytesWritten));
}

int UDPNetworkDevice::write(
   const void *buffer,   
   size_t numBytes 
)
{
   size_t bytesWritten;
   return(write(buffer, numBytes, _remote.sockaddr, bytesWritten));
}


