/**
* $Id: UDPNetworkDevice.h 5100 2009-12-04 20:54:54Z nei18232 $
*
* Class UDPNetworkDevice is derived from class NetworkDevice and 
* provides access to UDP network devices via the standard 
* sockets interface. 
*
* Events generated by this device: 
*  
*    READ_EVENT - Data has been received
*/
#ifndef UDPNetworkDevice_H
#define UDPNetworkDevice_H

#include "NetworkDevice.h"

class UDPNetworkDevice : public NetworkDevice
{
public:

   /**
   * Constructor
   *
   * @param side Side of network connection
   * @param host Host name
   * @param port Port number
   * @param persistArp <code>true</code> to resolve <code>host</code> and persist its MAC address in 
   *                    ARP table (calls to write will fail if unable to resolve/persist host MAC address).
   *                    Defaults to <code>true</code>.
   */
   UDPNetworkDevice(NetworkSide side,
                    const string &host,
                    unsigned short port,
                    bool persistArp = true);

   /**
   * Method open opens a UDP network connection
   *
   * @return Status of operation
   */
   virtual int open();
   
   /**
   * Method read reads data on a UDP network connection.
   *
   * @param buffer Buffer
   * @param maxBytes Maximum bytes to read
   * @param bytesRead Bytes read
   * @return Status of operation
   */
   virtual int read(
      char *buffer,     
      size_t maxBytes,  
      size_t &bytesRead 
   );

   /**
   * Method read reads data on a UDP network connection.
   *
   * @param buffer Buffer
   * @param maxBytes Maximum bytes to read
   * @param bytesRead Bytes read
   * @param from Host data was received from
   * @return Status of operation
   */
   int read(
      char *buffer,     
      size_t maxBytes,  
      size_t &bytesRead,
      struct sockaddr &from
   );

   /**
   * Method write writes data to a UDP network connection.
   *
   * @param buffer Buffer
   * @param numBytes Number of bytes to write
   * @param bytesWritten Bytes written
   * @return Status of operation
   */
   virtual int write(
      const void *buffer,        
      size_t numBytes,     
      size_t &bytesWritten 
   );

   /**
   * Method write writes data to a UDP network connection.
   *
   * @param buffer Buffer
   * @param numBytes Number of bytes to write
   * @return Status of operation
   */
   virtual int write(
      const void *buffer,   
      size_t numBytes 
   );

   /**
   * Method write writes data to a UDP network connection.
   *
   * @param buffer Buffer
   * @param numBytes Number of bytes to write
   * @param to Host to send data to
   * @param bytesWritten Bytes written
   * @return Status of operation
   */
   int write(
      const void *buffer,           
      size_t numBytes,        
      struct sockaddr_in &to, 
      size_t &bytesWritten    
   );

   /**
   * Method getSendingHost returns the sockaddr structure for the 
   * last host that sent UDP data to this device. 
   *
   * @return Sockaddr data
   */
   inline struct sockaddr &getSendingHost();

private:

   struct sockaddr _from;

   /**
    * <code>true</code> if either ARP was requested to be persisted and it was persisted
    * or ARP was not requested to be persisted.
    * <code>false</code> if ARP was requested to be persisted and has not yet been persisted.
    */
   bool   arpPersisted;
};

struct sockaddr &UDPNetworkDevice::getSendingHost()
{
   return(_from);
}

#endif
