#!/bin/sh

# Test Server: 172.16.80.10
# DU-A: 172.16.80.11
# DU-B: 172.16.80.12
# TU:   172.16.80.13

mkdir /mnt/sd-mmcblk0p1
mount /dev/mmcblk0p1 /mnt/sd-mmcblk0p1

mkdir /mnt/sd-mmcblk0p2
mount /dev/mmcblk0p2 /mnt/sd-mmcblk0p2

ifconfig eth0 172.16.80.49 netmask 255.255.255.0
ping -c 1 172.16.80.30
ping -c 1 172.16.80.111
# /mnt/sd-mmcblk0p1/bin/swc-esw-app DU &
