#!/bin/sh

# ZCU104: 172.16.80.8
# CS: 172.16.80.9
# TR: 172.16.80.12

mkdir /mnt/sd-mmcblk0p1
mount /dev/mmcblk0p1 /mnt/sd-mmcblk0p1

mkdir /mnt/sd-mmcblk0p2
mount /dev/mmcblk0p2 /mnt/sd-mmcblk0p2

ifconfig eth0 172.16.80.49 netmask 255.255.255.0
ping -c 1 172.16.80.30
ping -c 1 172.16.80.111
# /mnt/sd-mmcblk0p1/bin/swic-emsw-app.elf DR &
