#
# $Id: devices.conf 8216 2013-07-31 22:12:44Z tra18693 $
#
# Use by both CSP TWGS and BS TWGS
#
# Device configurations
#
# Supported types and their settings:
#
# UDP - UDP-based network device
#   host
#   port
#
# TCP - TCP-based network device
#   host
#   port
#   connectTimeout - in seconds.  defaults to 75
#
# PIPE - Named pipe
#   name           - defaults to "/pipe/" + sectionName
#   maxMsgs        - max number of messages the pipe can hold
#   maxMsgSize     - max size (in bytes) of any message
#
# AXIS - AxisFlow
#   outboundChannel - name of channel to write to if created for output
#   inboundChannel - name of channel to read from if created for input
#   queueSize      - number of messages to queue up (used by input side only)
#
# MULTICAST - a single device that writes to multiple devices
#   devices        - comma-separated list of devices defined elsewhere in this file
#
# DDR - The Pentek 7142. It has no settings.
#
# TIMESTAMP - Device used to timestamp baseband data.
#   present - set to "true" if an IRIG card is present, else "false"
#
# ALIAS - simple alias for another device
#   aliasFor       - name of other device
#

#**************************************
# Channel Sim Devices
#**************************************
FromRIMS
    type=UDP
    host=172.16.8.3
    port=21568
