#
# $Id: logger.conf 5384 2010-02-05 19:09:48Z ste38548 $
#
#
# Configure logging levels for compilation units on the various nodes.
# Reference nodes.conf for delegation of each task to each node.
#
# Valid log levels include:
#   Disabled (= no logger output to occur per logger name)
#   error
#   warn
#   info
#   debug
#   trace
#
# Special cases
#   !default     - the default log level to use for this node if not otherwise set
#                - defaults to "info"
#   !consoleEcho - everything at this level or above gets written to the local console
#                - only effective if the compilation unit's level is also enabled
#                - defaults to "info"
#
# TWGS architecture / task deployment:
#   Node    Task                                Logger name
#  ------  -------------------------           -------------------------
#    0      TWGS1_StatusManager                 (none)
#           TWGS1_EnterpriseCmdMgr              (none)
#           TWGS1_TransceiverMonitor            TWGS1_TransceiverMonitor.debug
#   
#    1      TWGS1_Node1_RemoteStatusMgr         (none)
#           TWGS1_RadarCommandManager           (none)
#           TWGS1_PBPManager                    PBPMgr.debug
#           TWGS1_Node1_RemoteEnterpriseCmdMgr  (none)
#           TWGS1_DiagnositcsMgr                (none)
#   
#    2      TWGS2_Node0_RemoteStatusMgr         (none)
#           TWGS2_Node0_RemoteEnterpriseCmdMgr  (none)
#           TWGS2_RFGenMonitor                  (none)
#   
#    3      TWGS2_Node1_RemoteStatusMgr         TWGSRemoteStatusMgr
#           TWGS2_Node1_RemoteEnterpriseCmdMgr  (none)
#           TWGS2_PBPManager                    (none)
#           TWGS2_DiagnosticsMgr                (none)
#           TWGS_COTSHWMgr                      (none)
#

log.levels.node:0
    !default=debug
    !consoleEcho=disabled
    Notification=trace
#   RFGeneratorDevice=debug
#   TWGS1_TransceiverMonitor=trace

log.levels.node:1
    !default=debug
    !consoleEcho=disabled
    Notification=trace
#   CommandMgr.procRimsCmdDev=trace
#   HWActionMgr=debug
#   PBPMgr=trace
#   RFGenActionMgr.addGatedAction=debug
#   RFGenActionMgr.addTestTargetAction=debug
#   RFGeneratorDevice=debug
#   TransceiverActionMgr=debug

log.levels.node:2
    !default=debug
    !consoleEcho=disabled
    Notification=trace
#   RFGeneratorDevice=debug

log.levels.node:3
    !default=debug
    !consoleEcho=disabled
    Notification=trace
#   RFGeneratorDevice=debug
#   TWGSRemoteStatusMgr=debug

################################################################################
# Known logger names, as of 1/24/11 (JSteiger):
#       - To obtain, file search the TWGS source for "logger(".
#TWGS1_TransceiverMonitor.debug
#HWActionMgr.debug
#RFGenActionMgr.addGatedAction
#RFGenActionMgr.addTestTargetAction
#TransceiverActionMgr.debug
#PBPMgr.debug
#TWGSRemoteStatusMgr
#RFGeneratorDevice.debug
################################################################################

